namespace Localization.Xliff.OM.Modules.TranslationCandidates
{
    /// <summary>
    /// Defines the type of a <see cref="Match"/> element.
    /// </summary>
    public enum MatchType
    {
        /// <summary>
        /// Assembled Match: candidate generated by assembling parts of different translations.
        /// </summary>
        /// <example>Constructing a candidate by using the known translations of various spans of content of
        /// the source. </example>
        AssembledMatch,

        /// <summary>
        /// Identifier-based Match: candidate that has an identifier identical to the one of the source content.
        /// </summary>
        /// <example>The previous translation of a given UI component with the same Id. match that has an identifier
        /// identical to the source content.</example>
        IdentifierMatch,

        /// <summary>
        /// In Context Match: candidate for which the content context of the translation was the same as the one
        /// of the current source.
        /// </summary>
        /// <example>The source text for both contents is also preceded and/or followed by an identical source
        /// segment, or both appear as e.g. level 2 headings.</example>
        InContextMatch,

        /// <summary>
        /// Machine Translation: candidate generated by a machine translation system.
        /// </summary>
        MachineTranslation,

        /// <summary>
        /// Candidate of a top level type not covered by any of the above definitions.
        /// </summary>
        Other,

        /// <summary>
        /// Term Base: candidate obtained from a terminological database, i.e. the whole source segment matches
        /// with a source term base entry.
        /// </summary>
        TermBase,

        /// <summary>
        /// Translation Memory: candidate based on a simple match of the source content.
        /// </summary>
        TranslationMemory
    }
}
