//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Xliff.OM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Xliff.OM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be completed because the {0} element is already a child of another XliffElement..
        /// </summary>
        internal static string ArgValidator_ElementReused_Format {
            get {
                return ResourceManager.GetString("ArgValidator_ElementReused_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id &apos;{0}&apos; contains some invalid characters. The Id must be an NMTOKEN..
        /// </summary>
        internal static string ArgValidator_InvalidId_Format {
            get {
                return ResourceManager.GetString("ArgValidator_InvalidId_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not a type of {1}..
        /// </summary>
        internal static string ArgValidator_InvalidType_Format {
            get {
                return ResourceManager.GetString("ArgValidator_InvalidType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not a valid type..
        /// </summary>
        internal static string ArgValidator_InvalidTypeOfMany_Format {
            get {
                return ResourceManager.GetString("ArgValidator_InvalidTypeOfMany_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string &apos;{0}&apos; must start with &apos;{1}&apos;..
        /// </summary>
        internal static string ArgValidator_StringDoesNotStartWith_Format {
            get {
                return ResourceManager.GetString("ArgValidator_StringDoesNotStartWith_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified {0} is not a descendant of one of: {1}..
        /// </summary>
        internal static string Codec_ElementNotDescendant_Format {
            get {
                return ResourceManager.GetString("Codec_ElementNotDescendant_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified {0} elements are not all descendants of the same {1}..
        /// </summary>
        internal static string Codec_ElementsNotDescendantOfSame_Format {
            get {
                return ResourceManager.GetString("Codec_ElementsNotDescendantOfSame_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text for the {0} cannot be null..
        /// </summary>
        internal static string Codec_TextCannotForElementBeNull_Format {
            get {
                return ResourceManager.GetString("Codec_TextCannotForElementBeNull_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-point U+{0:X4} is valid in XML and must not be encoded with &lt;cp/&gt;..
        /// </summary>
        internal static string CodePoint_InvalidCode {
            get {
                return ResourceManager.GetString("CodePoint_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code-point value: {0}..
        /// </summary>
        internal static string CodePoint_OutOfRange {
            get {
                return ResourceManager.GetString("CodePoint_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not supported by {1}..
        /// </summary>
        internal static string ConverterBase_ValueNotImplemented_Format {
            get {
                return ResourceManager.GetString("ConverterBase_ValueNotImplemented_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Space is restricted to Preserve..
        /// </summary>
        internal static string Data_SpaceRestriction {
            get {
                return ResourceManager.GetString("Data_SpaceRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inline tag of type &apos;{0}&apos; with Id &apos;{1}&apos; has CanCopy set to false yet was copied in the target..
        /// </summary>
        internal static string StandardValidator_CanCopyFailure_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CanCopyFailure_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for CanCopy and CanDelete must be set to false if CanReorder is not set to Yes..
        /// </summary>
        internal static string StandardValidator_CanCopyOrDeleteInvalidForCanReorder {
            get {
                return ResourceManager.GetString("StandardValidator_CanCopyOrDeleteInvalidForCanReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inline tag of type &apos;{0}&apos; with Id &apos;{1}&apos; has CanDelete set to false yet was deleted in the target. A tag matching the type and Id must be present in the target..
        /// </summary>
        internal static string StandardValidator_CanDeleteFailure_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CanDeleteFailure_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Type must be specified..
        /// </summary>
        internal static string StandardValidator_CodeBaseTypeNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_CodeBaseTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot have a CopyOf reference and an original data reference..
        /// </summary>
        internal static string StandardValidator_CodeBaseWithCopyOfAndDataRef_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CodeBaseWithCopyOfAndDataRef_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {0}.CopyOf does not refer to a valid {0}..
        /// </summary>
        internal static string StandardValidator_CopyOfNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_CopyOfNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence is invalid because the element doesn&apos;t have the same hierarchy as that of the source..
        /// </summary>
        internal static string StandardValidator_DifferentSequenceHierarchy {
            get {
                return ResourceManager.GetString("StandardValidator_DifferentSequenceHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document target language should be present only when Target elements are present. Check that both are present or neither are present..
        /// </summary>
        internal static string StandardValidator_DocumentTargetLanguageNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_DocumentTargetLanguageNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document Version cannot be null or empty string..
        /// </summary>
        internal static string StandardValidator_DocumentVersionNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_DocumentVersionNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id &apos;{0}&apos; for extension &apos;{1}&apos; (xmlns=&apos;{2}&apos;) is a duplicate across siblings..
        /// </summary>
        internal static string StandardValidator_DuplicateExtensionId_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateExtensionId_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id &apos;{0}&apos; is a duplicate across siblings..
        /// </summary>
        internal static string StandardValidator_DuplicateId_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateId_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id &apos;{0}&apos; for the {1} is a duplicate within the elements of the {2}..
        /// </summary>
        internal static string StandardValidator_DuplicateIdWithinHierarchy_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateIdWithinHierarchy_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order &apos;{0}&apos; is a duplicate across siblings..
        /// </summary>
        internal static string StandardValidator_DuplicateOrder_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateOrder_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate reference to a {0} with Id {1} cannot be used..
        /// </summary>
        internal static string StandardValidator_DuplicateReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_DuplicateReference_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} with Id {1} was not found..
        /// </summary>
        internal static string StandardValidator_ElementNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ElementNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must not contain only whitespace..
        /// </summary>
        internal static string StandardValidator_EmptyString_Format {
            get {
                return ResourceManager.GetString("StandardValidator_EmptyString_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for {0} must be specified when a value for {1} is specified..
        /// </summary>
        internal static string StandardValidator_ExplicitDependencyMissing_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ExplicitDependencyMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for SubFormatStyle cannot be present unless a value for FormatStyle is specified..
        /// </summary>
        internal static string StandardValidator_FormatStyleSubFormatWithoutFormat {
            get {
                return ResourceManager.GetString("StandardValidator_FormatStyleSubFormatWithoutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for FormatStyle cannot be present on a SpanningCodeEnd unless the Isolated value is set to true..
        /// </summary>
        internal static string StandardValidator_FormatStyleWithSpanEndNotIsolated {
            get {
                return ResourceManager.GetString("StandardValidator_FormatStyleWithSpanEndNotIsolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The glossary entry must contain at least a translation or a definition..
        /// </summary>
        internal static string StandardValidator_GlossaryEntryMissingChildren {
            get {
                return ResourceManager.GetString("StandardValidator_GlossaryEntryMissingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HRef should be present only when NonTranslatableText elements are not present. Check that either HRef is specified or NonTranslatableText, but not both..
        /// </summary>
        internal static string StandardValidator_HRefNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_HRefNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HRef should be present only when the {0} is empty. Check that either HRef is specified or {0} is empty, but not both..
        /// </summary>
        internal static string StandardValidator_HRefNotSpecifiedWhenEmpty_Format {
            get {
                return ResourceManager.GetString("StandardValidator_HRefNotSpecifiedWhenEmpty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HRef cannot be null or empty string..
        /// </summary>
        internal static string StandardValidator_HRefNotSpecifiedWhenRequired {
            get {
                return ResourceManager.GetString("StandardValidator_HRefNotSpecifiedWhenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id cannot be null or empty string..
        /// </summary>
        internal static string StandardValidator_IdNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_IdNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target contains a {0} tag with Id &apos;{1}&apos; that is not equivalent to the type of tag in Source ({2}) with the same Id..
        /// </summary>
        internal static string StandardValidator_InlineTagsDontMatch_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InlineTagsDontMatch_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {0}.CopyOf ({1}) refers to an invalid element or an element of another type..
        /// </summary>
        internal static string StandardValidator_InvalidCopyOfElement_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidCopyOfElement_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} ({1}) does not refer to a valid Data element..
        /// </summary>
        internal static string StandardValidator_InvalidDataReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidDataReference_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reference ({0}) must refer to a valid {1} within the enclosing Unit..
        /// </summary>
        internal static string StandardValidator_InvalidMarkedSpanReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidMarkedSpanReference_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reference ({0}) is not a well-formed selector path..
        /// </summary>
        internal static string StandardValidator_InvalidMarkedSpanReferenceSelectorPath_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidMarkedSpanReferenceSelectorPath_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type value must be either &quot;comment&quot;, &quot;generic&quot;, &quot;term&quot;, or a be in the format of &apos;prefix:value&apos; where prefix must not be &apos;xlf&apos; and prefix and value must not be empty strings..
        /// </summary>
        internal static string StandardValidator_InvalidMarkedSpanType {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidMarkedSpanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Order must be greater than 0 and less than {0}..
        /// </summary>
        internal static string StandardValidator_InvalidOrder_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidOrder_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be null or be in the format of &apos;prefix:value&apos; where prefix must not be &apos;xlf&apos; and prefix and value must not be empty strings..
        /// </summary>
        internal static string StandardValidator_InvalidPrefix_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidPrefix_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Priority must be between {0} and {1}..
        /// </summary>
        internal static string StandardValidator_InvalidPriority_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidPriority_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not a supported type of ResourceStringContent..
        /// </summary>
        internal static string StandardValidator_InvalidResourceStringContent_Format {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidResourceStringContent_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for SubType must be null or be in the format of &apos;prefix:value&apos; prefix and value must not be empty strings. If prefix is &quot;xlf&quot; then the value must be one of &quot;b&quot;, &quot;i&quot;, &quot;lb&quot;, &quot;pb&quot;, or &quot;u&quot;..
        /// </summary>
        internal static string StandardValidator_InvalidXliffSubTypeValue {
            get {
                return ResourceManager.GetString("StandardValidator_InvalidXliffSubTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property value on the Item must be &apos;content&apos; or the name of an attribute relating to the revision data..
        /// </summary>
        internal static string StandardValidator_ItemPropertyNull {
            get {
                return ResourceManager.GetString("StandardValidator_ItemPropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not BCP-47 compliant. Refer to http://tools.ietf.org/html/bcp47 for more information..
        /// </summary>
        internal static string StandardValidator_LanguageInvalid_Format {
            get {
                return ResourceManager.GetString("StandardValidator_LanguageInvalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target language must match the document language..
        /// </summary>
        internal static string StandardValidator_LanguageMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_LanguageMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document source language cannot be null or empty string..
        /// </summary>
        internal static string StandardValidator_LanguageNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_LanguageNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The marked span must have either a valid Reference or a Value, but not both..
        /// </summary>
        internal static string StandardValidator_MarkedSpanReferenceAndValueSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_MarkedSpanReferenceAndValueSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for MimeType is required because the Source and Target elements are both empty..
        /// </summary>
        internal static string StandardValidator_MimeTypeRequired {
            get {
                return ResourceManager.GetString("StandardValidator_MimeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element must contain one or more {0}..
        /// </summary>
        internal static string StandardValidator_NoElements_Format {
            get {
                return ResourceManager.GetString("StandardValidator_NoElements_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SourceReference {0} does not refer to a valid Source span..
        /// </summary>
        internal static string StandardValidator_NoMatchingSourceReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_NoMatchingSourceReference_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Index must be greater than 0..
        /// </summary>
        internal static string StandardValidator_NonPositiveIndex {
            get {
                return ResourceManager.GetString("StandardValidator_NonPositiveIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for {0} must be specified..
        /// </summary>
        internal static string StandardValidator_OutputResolverFailed_Format {
            get {
                return ResourceManager.GetString("StandardValidator_OutputResolverFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Profile value in the ProfileData cannot be null or empty string..
        /// </summary>
        internal static string StandardValidator_ProfileNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_ProfileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} contains some characters that do not conform to an NMTOKEN..
        /// </summary>
        internal static string StandardValidator_PropertyNotNMTOKEN_Format {
            get {
                return ResourceManager.GetString("StandardValidator_PropertyNotNMTOKEN_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be null or empty string..
        /// </summary>
        internal static string StandardValidator_PropertyNotSpecified_Format {
            get {
                return ResourceManager.GetString("StandardValidator_PropertyNotSpecified_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceData must contain at least one ResourceItem or ResourceItemRef..
        /// </summary>
        internal static string StandardValidator_ResourceDataMissingItems {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceDataMissingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceItem must contain at least one of Source, Target, or Reference..
        /// </summary>
        internal static string StandardValidator_ResourceItemMissingChildren {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceItemMissingChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ResourceItem element with Id &apos;{0}&apos; was not found. Check that the Reference is valid and refers to a valid ResourceItem..
        /// </summary>
        internal static string StandardValidator_ResourceItemRefInvalidReference_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceItemRefInvalidReference_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ResourceItem must have a valid Source when Context is set to false..
        /// </summary>
        internal static string StandardValidator_ResourceItemSourceMissingWithNoContext {
            get {
                return ResourceManager.GetString("StandardValidator_ResourceItemSourceMissingWithNoContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rule must have exactly one of EndsWith, IsNotPresent, IsPresent, StartsWith, or a custom rule defined in an extension attribute..
        /// </summary>
        internal static string StandardValidator_RuleDefinitionInvalid {
            get {
                return ResourceManager.GetString("StandardValidator_RuleDefinitionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rule must have exactly one of EndsWith, IsPresent, StartsWith when ExistsInSource is set to true..
        /// </summary>
        internal static string StandardValidator_RuleExistsInSourceInvalid {
            get {
                return ResourceManager.GetString("StandardValidator_RuleExistsInSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SizeInfoReference should be present only when SizeInfo is not present. Check that either SizeInfoReference is specified or SizeInfo, but not both..
        /// </summary>
        internal static string StandardValidator_SameSizeInfoAndSizeInfoReferencePresence {
            get {
                return ResourceManager.GetString("StandardValidator_SameSizeInfoAndSizeInfoReferencePresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence is invalid because the element&apos;s selectable ancestor is outside the hierarchy of the element that starts the sequence..
        /// </summary>
        internal static string StandardValidator_SequenceAncestorNotInHierarchy {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceAncestorNotInHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence of inline tags cannot begin with one whose CanReorder value is set to No. The first inline tag in a sequence must begin with FirstNo..
        /// </summary>
        internal static string StandardValidator_SequenceCannotBeginWithNo {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceCannotBeginWithNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence of inline tags starting with type &apos;{0}&apos; and Id &apos;{1}&apos; was found in the target but it doesn&apos;t contain the same element types and Ids as that defined in the source. Expected to find {2}..
        /// </summary>
        internal static string StandardValidator_SequenceDoesntMatch_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceDoesntMatch_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Type:&apos;{0}&apos;, Id:&apos;{1}&apos;),.
        /// </summary>
        internal static string StandardValidator_SequenceEntry_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceEntry_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence of inline tags starting with type &apos;{0}&apos; and Id &apos;{1}&apos; was not found in the target..
        /// </summary>
        internal static string StandardValidator_SequenceNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SequenceNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for {0} cannot be present on a SpanningCodeEnd unless the Isolated value is set to true..
        /// </summary>
        internal static string StandardValidator_SizeRestrictionAttributeWithSpanEndNotIsolated_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SizeRestrictionAttributeWithSpanEndNotIsolated_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Source language must match the document source language..
        /// </summary>
        internal static string StandardValidator_SourceLanguageMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_SourceLanguageMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element must contain a Source element..
        /// </summary>
        internal static string StandardValidator_SourceNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_SourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Space is restricted to Preserve..
        /// </summary>
        internal static string StandardValidator_Space_Not_Preserve {
            get {
                return ResourceManager.GetString("StandardValidator_Space_Not_Preserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SpanningCodeEnd cannot have Isolated set to true because it has a StartReference..
        /// </summary>
        internal static string StandardValidator_SpanningCodeEndIslatedAndStartRef {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeEndIslatedAndStartRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SpanningCodeEnd cannot have Isolated set to false because it does not have a StartReference..
        /// </summary>
        internal static string StandardValidator_SpanningCodeEndNotIslatedOrStartRef {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeEndNotIslatedOrStartRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SpanningCodeEnd cannot have both a StartReference and an Id..
        /// </summary>
        internal static string StandardValidator_SpanningCodeEndStartRefAndId {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeEndStartRefAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SpanningCodeStart cannot have Isolated set to true because it is referred to by a SpanningCodeEnd ({0})..
        /// </summary>
        internal static string StandardValidator_SpanningCodeStartIslatedWithRef_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeStartIslatedWithRef_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SpanningCodeStart must have Isolated set to true because there are no SpanningCodeEnd elements that reference the element..
        /// </summary>
        internal static string StandardValidator_SpanningCodeStartNotIslated {
            get {
                return ResourceManager.GetString("StandardValidator_SpanningCodeStartNotIslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of CanReorder must be equivalent between the SpanningCodeStart and the SpanningCodeEnd. If CanReorder in the SpanningCodeStart is set to FirstNo or No, then the value for SpanningCodeEnd must be set to No. Otherwise the value must be set to Yes..
        /// </summary>
        internal static string StandardValidator_StartEndCanReorderMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_StartEndCanReorderMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {0} must be the same between the {1} and the {2}..
        /// </summary>
        internal static string StandardValidator_StartEndPropertyMismatch_Format {
            get {
                return ResourceManager.GetString("StandardValidator_StartEndPropertyMismatch_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is placed after its corresponding {1}..
        /// </summary>
        internal static string StandardValidator_StartTagOccursAfterEndTag_Format {
            get {
                return ResourceManager.GetString("StandardValidator_StartTagOccursAfterEndTag_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Unit matching the {0} value of {1} was not found..
        /// </summary>
        internal static string StandardValidator_SubflowNotFound_Format {
            get {
                return ResourceManager.GetString("StandardValidator_SubflowNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Target language must match the document target language..
        /// </summary>
        internal static string StandardValidator_TargetLanguageMismatch {
            get {
                return ResourceManager.GetString("StandardValidator_TargetLanguageMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element must contain a Target element..
        /// </summary>
        internal static string StandardValidator_TargetNotSpecified {
            get {
                return ResourceManager.GetString("StandardValidator_TargetNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred. See InnerException for details..
        /// </summary>
        internal static string StandardValidator_UnhandledException {
            get {
                return ResourceManager.GetString("StandardValidator_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} must be {1} or greater..
        /// </summary>
        internal static string StandardValidator_ValueMustBeNOrGreater_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ValueMustBeNOrGreater_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} is not in the range of {1} - {2}..
        /// </summary>
        internal static string StandardValidator_ValueNotInRange_Format {
            get {
                return ResourceManager.GetString("StandardValidator_ValueNotInRange_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type value must be set to Formatting when the SubType is one of &quot;xlf:b&quot;, &quot;xlf:i&quot;, &quot;xlf:lb&quot;, &quot;xlf:&quot;pb&quot;, &quot;xlf:u&quot;..
        /// </summary>
        internal static string StandardValidator_XliffSubTypeMismatchFormatting {
            get {
                return ResourceManager.GetString("StandardValidator_XliffSubTypeMismatchFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type value must be set to UserInterface when the SubType is &quot;xlf:var&quot;..
        /// </summary>
        internal static string StandardValidator_XliffSubTypeMismatchUserInterface {
            get {
                return ResourceManager.GetString("StandardValidator_XliffSubTypeMismatchUserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backslash (\) is not a valid character in the key portion of a format style. If a backslash is desired, it must be escaped using a backslash (ie. &quot;\\&quot;).
        /// </summary>
        internal static string SubFormatStyleConverter_BackslashInKey {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_BackslashInKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comma (,) is not a valid character in the value portion of a format style (key=&apos;{0}&apos;). If a comma is desired, it must be escaped using a backslash (ie. &quot;\,&quot;).
        /// </summary>
        internal static string SubFormatStyleConverter_CommaInValue_Format {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_CommaInValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key ({0}) for the format style is invalid because it does not represent a valid Xml name. See the inner exception for details..
        /// </summary>
        internal static string SubFormatStyleConverter_InvalidKey_Format {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_InvalidKey_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format style (key=&apos;{0}&apos;) is malformed because a value is not present. The style must contain a key and a value separated by a comma (,)..
        /// </summary>
        internal static string SubFormatStyleConverter_KeyWithoutValue_Format {
            get {
                return ResourceManager.GetString("SubFormatStyleConverter_KeyWithoutValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target must have corresponding Source..
        /// </summary>
        internal static string Utilities_TargetMustHaveSource {
            get {
                return ResourceManager.GetString("Utilities_TargetMustHaveSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id cannot be set on this element..
        /// </summary>
        internal static string XliffDocument_SetIdNotSupported {
            get {
                return ResourceManager.GetString("XliffDocument_SetIdNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attribute with the name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string XliffElement_AttributeAlreadyRegistered_Format {
            get {
                return ResourceManager.GetString("XliffElement_AttributeAlreadyRegistered_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The {0} already contains a value for {1} and cannot store another instance..
        /// </summary>
        internal static string XliffElement_ChildAlreadyExists_Format {
            get {
                return ResourceManager.GetString("XliffElement_ChildAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order of elements in the {0} is invalid starting with the element of type {1} ({2}:{3})..
        /// </summary>
        internal static string XliffElement_ElementOutOfOrder_Format {
            get {
                return ResourceManager.GetString("XliffElement_ElementOutOfOrder_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not support inner text..
        /// </summary>
        internal static string XliffElement_InnerTextNotSupported_Format {
            get {
                return ResourceManager.GetString("XliffElement_InnerTextNotSupported_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid child type for &apos;{1}&apos;..
        /// </summary>
        internal static string XliffElement_InvalidElement_Format {
            get {
                return ResourceManager.GetString("XliffElement_InvalidElement_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} is not supported..
        /// </summary>
        internal static string XliffElement_PropertyNotSupported_Format {
            get {
                return ResourceManager.GetString("XliffElement_PropertyNotSupported_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element named &apos;{0}&apos; is an invalid child for the {1} element..
        /// </summary>
        internal static string XliffElement_UnknownElement_Format {
            get {
                return ResourceManager.GetString("XliffElement_UnknownElement_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handler for namespace {0} is already registered..
        /// </summary>
        internal static string XliffReader_ExtensionAlreadyRegistered_Format {
            get {
                return ResourceManager.GetString("XliffReader_ExtensionAlreadyRegistered_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notes element within the element with selector path &apos;{0}&apos; must contain at least one note element..
        /// </summary>
        internal static string XliffReader_INoteContainerMissingNote_Format {
            get {
                return ResourceManager.GetString("XliffReader_INoteContainerMissingNote_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is not supported on the {1} element..
        /// </summary>
        internal static string XliffReader_InvalidAttributeName_Format {
            get {
                return ResourceManager.GetString("XliffReader_InvalidAttributeName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The originalData element within the element with selector path &apos;{0}&apos; must contain at least one data element..
        /// </summary>
        internal static string XliffReader_OriginalDataMissingData {
            get {
                return ResourceManager.GetString("XliffReader_OriginalDataMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize the object of type {0} because it is not part of a document..
        /// </summary>
        internal static string XliffWriter_CannotSerializeElement_Format {
            get {
                return ResourceManager.GetString("XliffWriter_CannotSerializeElement_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} element does not support {1} extensions..
        /// </summary>
        internal static string XliffWriter_ExtensionTypeNotSupported_Format {
            get {
                return ResourceManager.GetString("XliffWriter_ExtensionTypeNotSupported_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix {0} is already registered for a different namespace ({1})..
        /// </summary>
        internal static string XliffWriter_PrefixInUse_Format {
            get {
                return ResourceManager.GetString("XliffWriter_PrefixInUse_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the XML processing instruction does not conform to the XML specification..
        /// </summary>
        internal static string Xml_ProcessingInstruction_InvalidName_Format {
            get {
                return ResourceManager.GetString("Xml_ProcessingInstruction_InvalidName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalName must not contain &apos;:&apos; characters..
        /// </summary>
        internal static string XmlNameInfo_InvalidLocalName {
            get {
                return ResourceManager.GetString("XmlNameInfo_InvalidLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid XML prefix, namespace, and local name must be specified for the entity named &apos;{0}&apos;..
        /// </summary>
        internal static string XmlWriter_InvalidXmlSpecifier_Format {
            get {
                return ResourceManager.GetString("XmlWriter_InvalidXmlSpecifier_Format", resourceCulture);
            }
        }
    }
}
